import type { DashboardData } from "@/types/dashboard"

export function generateMockDashboard(): DashboardData {
  return {
    metrics: {
      tme_segundos: 83,
      tma_segundos: 245,
      taxa_contato: 68,
      taxa_conversao: 12,
      total_ligacoes: 347,
      total_contatos: 236,   // ~68% de 347 ligações efetivamente atendidas
      total_conversoes: 41,
      ligacoes_ativas: 4,
      sdrs_disponiveis: 3,
      sdrs_em_ligacao: 4,
      sdrs_offline: 1,
    },
    sdrs: [
      {
        id: "1",
        name: "Ana Beatriz",
        status: "em_ligacao",
        extension: "3001",
        meta_dia: 30,
        ligacoes_realizadas: 52,
        ligacoes_atendidas: 36,
        conversoes: 8,
        tma_segundos: 210,
        score_ia: 91,
      },
      {
        id: "2",
        name: "Carlos Mendes",
        status: "em_ligacao",
        extension: "3002",
        meta_dia: 30,
        ligacoes_realizadas: 48,
        ligacoes_atendidas: 31,
        conversoes: 6,
        tma_segundos: 255,
        score_ia: 84,
      },
      {
        id: "3",
        name: "Fernanda Lima",
        status: "disponivel",
        extension: "3003",
        meta_dia: 30,
        ligacoes_realizadas: 41,
        ligacoes_atendidas: 28,
        conversoes: 5,
        tma_segundos: 198,
        score_ia: 78,
      },
      {
        id: "4",
        name: "Rafael Costa",
        status: "em_ligacao",
        extension: "3004",
        meta_dia: 30,
        ligacoes_realizadas: 39,
        ligacoes_atendidas: 25,
        conversoes: 7,
        tma_segundos: 280,
        score_ia: 88,
      },
      {
        id: "5",
        name: "Julia Souza",
        status: "disponivel",
        extension: "3005",
        meta_dia: 30,
        ligacoes_realizadas: 44,
        ligacoes_atendidas: 30,
        conversoes: 6,
        tma_segundos: 230,
        score_ia: 82,
      },
      {
        id: "6",
        name: "Marcos Pinto",
        status: "em_ligacao",
        extension: "3006",
        meta_dia: 30,
        ligacoes_realizadas: 35,
        ligacoes_atendidas: 22,
        conversoes: 4,
        tma_segundos: 310,
        score_ia: 71,
      },
      {
        id: "7",
        name: "Larissa Neves",
        status: "disponivel",
        extension: "3007",
        meta_dia: 30,
        ligacoes_realizadas: 50,
        ligacoes_atendidas: 34,
        conversoes: 5,
        tma_segundos: 220,
        score_ia: 86,
      },
      {
        id: "8",
        name: "Diego Rocha",
        status: "offline",
        extension: "3008",
        meta_dia: 30,
        ligacoes_realizadas: 38,
        ligacoes_atendidas: 24,
        conversoes: 0,
        tma_segundos: 0,
        score_ia: 75,
      },
    ],
    live_calls: [
      {
        id: "c1",
        sdr_id: "1",
        sdr_name: "Ana Beatriz",
        school_name: "Colégio São Paulo",
        phone: "(11) 9****-4521",
        started_at: new Date(Date.now() - 185000).toISOString(),
        duration_seconds: 185,
        status: "em_andamento",
      },
      {
        id: "c2",
        sdr_id: "2",
        sdr_name: "Carlos Mendes",
        school_name: "Instituto Educação SP",
        phone: "(11) 9****-7832",
        started_at: new Date(Date.now() - 42000).toISOString(),
        duration_seconds: 42,
        status: "em_andamento",
      },
      {
        id: "c3",
        sdr_id: "4",
        sdr_name: "Rafael Costa",
        school_name: "Escola Técnica Progresso",
        phone: "(11) 9****-1290",
        started_at: new Date(Date.now() - 8000).toISOString(),
        duration_seconds: 8,
        status: "tocando",
      },
      {
        id: "c4",
        sdr_id: "6",
        sdr_name: "Marcos Pinto",
        school_name: "Faculdade Unimetro",
        phone: "(11) 9****-6644",
        started_at: new Date(Date.now() - 320000).toISOString(),
        duration_seconds: 320,
        status: "em_andamento",
      },
    ],
    top_objections: [
      { label: "Parcela muito alta", count: 52, percentage: 38 },
      { label: "Vou pensar e te retorno", count: 33, percentage: 24 },
      { label: "Já tenho financiamento", count: 21, percentage: 15 },
      { label: "Não tenho interesse agora", count: 17, percentage: 12 },
      { label: "Não conheço a Creditum", count: 15, percentage: 11 },
    ],
    occurrences: [
      { label: "Contrato Fechado",       count: 41,  percentage: 12, color: "bg-emerald-500" },
      { label: "Qualificação",           count: 78,  percentage: 22, color: "bg-blue-500"    },
      { label: "Agendamento Confirmado", count: 34,  percentage: 10, color: "bg-sky-400"     },
      { label: "Cliente Desligou",       count: 29,  percentage: 8,  color: "bg-red-500"     },
      { label: "Não Atendeu",            count: 88,  percentage: 25, color: "bg-gray-400"    },
      { label: "Caixa Postal",           count: 45,  percentage: 13, color: "bg-gray-300"    },
      { label: "Retornar Ligação",       count: 22,  percentage: 6,  color: "bg-yellow-500"  },
      { label: "Sem Interesse",          count: 10,  percentage: 3,  color: "bg-orange-500"  },
    ],
    hourly_chart: [
      { hora: "08h", ligacoes: 18, contatos: 12, conversoes: 2 },
      { hora: "09h", ligacoes: 35, contatos: 24, conversoes: 5 },
      { hora: "10h", ligacoes: 48, contatos: 33, conversoes: 7 },
      { hora: "11h", ligacoes: 52, contatos: 36, conversoes: 6 },
      { hora: "12h", ligacoes: 21, contatos: 14, conversoes: 2 },
      { hora: "13h", ligacoes: 38, contatos: 26, conversoes: 5 },
      { hora: "14h", ligacoes: 55, contatos: 38, conversoes: 8 },
      { hora: "15h", ligacoes: 44, contatos: 30, conversoes: 6 },
      { hora: "16h", ligacoes: 36, contatos: 25, conversoes: 0 },
    ],
    hourly_source: "from_calls" as const,
    last_updated: new Date().toISOString(),
  }
}
